# Generated by Django 4.0.4 on 2022-05-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rezume',
            new_name='Resume',
        ),
    ]
